services:
  mirage-server:
    image: hetkpatel/mirage-server:test
    container_name: mirage-server
    ports:
      - ${PORT}:5000
    volumes:
      - ${DRIVE_LOCATION}:/mirage/DRIVE
      - ./container/backup/:/mirage/backup # TO BE DEPRECATED
      - ./container/logs/:/mirage/logs
    restart: unless-stopped

  mirage-web:
    image: hetkpatel/mirage-web:test
    container_name: mirage-web
    ports:
      - 80:80
    depends_on:
      - mirage-server
    restart: unless-stopped
