# Use the official Nginx base image
FROM nginx:latest

# Install Git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /usr/share/nginx/html

# Clone the Git repository
RUN rm -f ./*
RUN git clone -b production --depth 1 --single-branch https://github.com/hetkpatel/Mirage-Client.git .

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
